version: "3"

services: 

    mongo:
        image: mongo
        ports:
            - 27018:27017
        container_name: mongodb-database

    redis:
        image: redis
        ports:
            - 6378:6379
        container_name: redis-cache

